#:kivy 1.0.9

<MainFrame>:
    Splitter:
        sizable_from: 'right'
        #keep_within_parent: in_parent_box.active
        #rescale_with_parent: rescale_box.active
        Display:
            id: disp_instance
    RightPane:

<RightPane>:
    Button:
        id: grual
        text: 'From kv file'
        on_press: root.activate()

<Display>:
    disp_prop: disp_lbl
    # num_prop: nummer
    Label:
        id: disp_lbl
        text: '100'
